package:
  name: "axtoolkit"       # 包名
  version: "0.1.3"         # 版本号

source:
  path: .                  # 本地构建

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"  # 使用 pip 安装

requirements:
  host:
    - python >=3.8         # 构建环境所需的依赖
    - pip                  # 使用 pip 打包
  build:
    - python >=3.8         # 构建时的依赖
    - psutil
    - matplotlib
    - rdkit
    - pathlib
    - setuptools
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - seaborn
    - joblib
    - pyyaml
    - pillow
    - peptides
    - snakemake
    - yaml 
  run:
    - python >=3.8         # 运行时的依赖
    - psutil
    - matplotlib
    - rdkit
    - pathlib
    - setuptools
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - seaborn
    - joblib
    - pyyaml
    - pillow
    - peptides
    - snakemake
    - yaml
    - htop
    - ipykernel
    - jupyter

about:
  home: "https://github.com/xinalbert/AXtoolkit"
  license: "MIT"
  summary: "A personal Python package example"
